---
apiVersion: v1
kind: Namespace
metadata:
  name: kibana
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: kibana
spec:
  version: 7.8.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
